## Create a new notebook for this task. Be sure to import the relevant libraries, along with your ords_prods_merge dataframe, which should include your newly derived columns from the previous Exercise.

In [1]:
# import libraries
import pandas as pd
import numpy as np
import os

 # 2. In this Exercise, you learned how to find the aggregated mean of the “order_number” column grouped by “department_id” for a subset of your dataframe. Now, repeat this process for the entire dataframe

In [2]:
path = r'C:\Users\jacks\OneDrive\Documents\Elise\Instacart-Basket'

In [5]:
ords_prods_merged = pd.read_pickle(os.path.join(path, '02 Data', 'prepared Data', 'orders_products_derived.pkl'))

In [6]:
ords_prods_merged.head()

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,...,price_range_loc,Busiest day,Busiest days,period_of_day,max_order,loyalty_flag,avg_price,spender_flag,median_days_since_prior_order,frequency_flag
0,2539329,1,1,2,8,NaN,196.0,1.0,0.0,Soda,...,Mid-range product,Regularly busy,Regularly busy,6am-11am,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
1,2398795,1,2,3,7,15.0,196.0,1.0,1.0,Soda,...,Mid-range product,Regularly busy,Slowest days,6am-11am,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
2,473747,1,3,3,12,21.0,196.0,1.0,1.0,Soda,...,Mid-range product,Regularly busy,Slowest days,12pm-5pm,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
3,2254736,1,4,4,7,29.0,196.0,1.0,1.0,Soda,...,Mid-range product,Least busy,Slowest days,6am-11am,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
4,431534,1,5,4,15,28.0,196.0,1.0,1.0,Soda,...,Mid-range product,Least busy,Slowest days,12pm-5pm,10,New customer,6.367797,Low spender,20.5,Non-frequent customer